appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: QibXC5Kc3W8nBwEokYQUXtNr6j1NlxCFID1O/ZVKNoVN85JNQg9Sxu724M84RoGAM+2v8gXG8uJmZt3ySmKm8qUbd0/ax/T8A/mAPHswoMTp6H+ge2sdZRai/I6Ipngd8izd8lS1zNuSuOKQVi0Zb1OmrLL7APJERxwlwRpy0ZNp3m9W5NQhIAmBvOyQ1HB8EVyYKgsrK3Va+pG5xwrpTPDumHv5W/dhY124cKbdeTjcn1ju+EVXUauKcn573Jx23PdYsGyOTUEmtkQEKqscSotnY1SZqesaeal8jjSty1TbA+SWSfDEgsMD+RC8qcxDeB3PbkZLr1GrgNcYK6Zfxn0T/ghH4SteboOJATg5S5jHZqJxD9aLEcHyZTDZyJ2zG7dD6L9CNcjAYL5J8qrxMjWG7PY95EATdsPsq5qWRqdR/Ac54qqeF3jkji6BUIsmgX0pLL0FcSlLcJvf+z0Y520WyKwsRBVKU2/O+jXBfW+/xiqJffMwRJefx59Rss3ShJJL1uV+qIFdKVO9W4GwgaWQF9Z3rzGcwF1Db9jlLYeovtmR7R+Z0HgoEccb4TkJrSSVWuP9D7A8Haran7x6E6H5foavM4AubT060BqQAtKHgxKo7nUp5cJJ79M7Z2Bjp5uHI2aaB238vPFDla2/1/waz6ykl/u4H3kJHsbwqb4=}
provider:
  win: azure
bot:
  automerge: true
